coffee_shop:
  outputs:
    dev:
      dbname: coffee_shop
      host: localhost
      pass: password
      port: 5432
      schema: dbt
      threads: 1
      type: postgres
      user: user
  target: dev
